spring:
  profiles:
    active: local

  mvc:
    view:
      prefix: /WEB-INF/jblog
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/blogservice
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace